// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: inventory-api/proto/schedule/schedule.proto

package schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchScheduleRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DepartureStationId   string                 `protobuf:"bytes,1,opt,name=departure_station_id,json=departureStationId,proto3" json:"departure_station_id,omitempty"`
	DestinationStationId string                 `protobuf:"bytes,2,opt,name=destination_station_id,json=destinationStationId,proto3" json:"destination_station_id,omitempty"`
	DepartureDate        string                 `protobuf:"bytes,3,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"` // ISO date "2025-11-09"
	PassengerCount       int32                  `protobuf:"varint,4,opt,name=passenger_count,json=passengerCount,proto3" json:"passenger_count,omitempty"`
	RoundTrip            bool                   `protobuf:"varint,5,opt,name=round_trip,json=roundTrip,proto3" json:"round_trip,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SearchScheduleRequest) Reset() {
	*x = SearchScheduleRequest{}
	mi := &file_inventory_api_proto_schedule_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchScheduleRequest) ProtoMessage() {}

func (x *SearchScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_proto_schedule_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchScheduleRequest.ProtoReflect.Descriptor instead.
func (*SearchScheduleRequest) Descriptor() ([]byte, []int) {
	return file_inventory_api_proto_schedule_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *SearchScheduleRequest) GetDepartureStationId() string {
	if x != nil {
		return x.DepartureStationId
	}
	return ""
}

func (x *SearchScheduleRequest) GetDestinationStationId() string {
	if x != nil {
		return x.DestinationStationId
	}
	return ""
}

func (x *SearchScheduleRequest) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *SearchScheduleRequest) GetPassengerCount() int32 {
	if x != nil {
		return x.PassengerCount
	}
	return 0
}

func (x *SearchScheduleRequest) GetRoundTrip() bool {
	if x != nil {
		return x.RoundTrip
	}
	return false
}

type SearchScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*TrainScheduleItem   `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchScheduleResponse) Reset() {
	*x = SearchScheduleResponse{}
	mi := &file_inventory_api_proto_schedule_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchScheduleResponse) ProtoMessage() {}

func (x *SearchScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_proto_schedule_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchScheduleResponse.ProtoReflect.Descriptor instead.
func (*SearchScheduleResponse) Descriptor() ([]byte, []int) {
	return file_inventory_api_proto_schedule_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *SearchScheduleResponse) GetSchedules() []*TrainScheduleItem {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type TrainScheduleItem struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TrainId                string                 `protobuf:"bytes,1,opt,name=train_id,json=trainId,proto3" json:"train_id,omitempty"`
	TrainName              string                 `protobuf:"bytes,2,opt,name=train_name,json=trainName,proto3" json:"train_name,omitempty"`
	TrainCode              string                 `protobuf:"bytes,3,opt,name=train_code,json=trainCode,proto3" json:"train_code,omitempty"`
	ClassName              string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	SubclassName           string                 `protobuf:"bytes,5,opt,name=subclass_name,json=subclassName,proto3" json:"subclass_name,omitempty"`
	DepartureStationName   string                 `protobuf:"bytes,6,opt,name=departure_station_name,json=departureStationName,proto3" json:"departure_station_name,omitempty"`
	DepartureTime          string                 `protobuf:"bytes,7,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	DestinationStationName string                 `protobuf:"bytes,8,opt,name=destination_station_name,json=destinationStationName,proto3" json:"destination_station_name,omitempty"`
	ArrivalTime            string                 `protobuf:"bytes,9,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	Duration               string                 `protobuf:"bytes,10,opt,name=duration,proto3" json:"duration,omitempty"`
	StartingPrice          float64                `protobuf:"fixed64,11,opt,name=starting_price,json=startingPrice,proto3" json:"starting_price,omitempty"`
	Available              bool                   `protobuf:"varint,12,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TrainScheduleItem) Reset() {
	*x = TrainScheduleItem{}
	mi := &file_inventory_api_proto_schedule_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainScheduleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainScheduleItem) ProtoMessage() {}

func (x *TrainScheduleItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_api_proto_schedule_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainScheduleItem.ProtoReflect.Descriptor instead.
func (*TrainScheduleItem) Descriptor() ([]byte, []int) {
	return file_inventory_api_proto_schedule_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *TrainScheduleItem) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *TrainScheduleItem) GetTrainName() string {
	if x != nil {
		return x.TrainName
	}
	return ""
}

func (x *TrainScheduleItem) GetTrainCode() string {
	if x != nil {
		return x.TrainCode
	}
	return ""
}

func (x *TrainScheduleItem) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *TrainScheduleItem) GetSubclassName() string {
	if x != nil {
		return x.SubclassName
	}
	return ""
}

func (x *TrainScheduleItem) GetDepartureStationName() string {
	if x != nil {
		return x.DepartureStationName
	}
	return ""
}

func (x *TrainScheduleItem) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *TrainScheduleItem) GetDestinationStationName() string {
	if x != nil {
		return x.DestinationStationName
	}
	return ""
}

func (x *TrainScheduleItem) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *TrainScheduleItem) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TrainScheduleItem) GetStartingPrice() float64 {
	if x != nil {
		return x.StartingPrice
	}
	return 0
}

func (x *TrainScheduleItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_inventory_api_proto_schedule_schedule_proto protoreflect.FileDescriptor

const file_inventory_api_proto_schedule_schedule_proto_rawDesc = "" +
	"\n" +
	"+inventory-api/proto/schedule/schedule.proto\"\xee\x01\n" +
	"\x15SearchScheduleRequest\x120\n" +
	"\x14departure_station_id\x18\x01 \x01(\tR\x12departureStationId\x124\n" +
	"\x16destination_station_id\x18\x02 \x01(\tR\x14destinationStationId\x12%\n" +
	"\x0edeparture_date\x18\x03 \x01(\tR\rdepartureDate\x12'\n" +
	"\x0fpassenger_count\x18\x04 \x01(\x05R\x0epassengerCount\x12\x1d\n" +
	"\n" +
	"round_trip\x18\x05 \x01(\bR\troundTrip\"J\n" +
	"\x16SearchScheduleResponse\x120\n" +
	"\tschedules\x18\x01 \x03(\v2\x12.TrainScheduleItemR\tschedules\"\xcb\x03\n" +
	"\x11TrainScheduleItem\x12\x19\n" +
	"\btrain_id\x18\x01 \x01(\tR\atrainId\x12\x1d\n" +
	"\n" +
	"train_name\x18\x02 \x01(\tR\ttrainName\x12\x1d\n" +
	"\n" +
	"train_code\x18\x03 \x01(\tR\ttrainCode\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\x12#\n" +
	"\rsubclass_name\x18\x05 \x01(\tR\fsubclassName\x124\n" +
	"\x16departure_station_name\x18\x06 \x01(\tR\x14departureStationName\x12%\n" +
	"\x0edeparture_time\x18\a \x01(\tR\rdepartureTime\x128\n" +
	"\x18destination_station_name\x18\b \x01(\tR\x16destinationStationName\x12!\n" +
	"\farrival_time\x18\t \x01(\tR\varrivalTime\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\tR\bduration\x12%\n" +
	"\x0estarting_price\x18\v \x01(\x01R\rstartingPrice\x12\x1c\n" +
	"\tavailable\x18\f \x01(\bR\tavailable2J\n" +
	"\rTrainSchedule\x129\n" +
	"\x06Search\x12\x16.SearchScheduleRequest\x1a\x17.SearchScheduleResponseBBZ@github.com/pujidjayanto/choochoohub/inventory-api/proto/scheduleb\x06proto3"

var (
	file_inventory_api_proto_schedule_schedule_proto_rawDescOnce sync.Once
	file_inventory_api_proto_schedule_schedule_proto_rawDescData []byte
)

func file_inventory_api_proto_schedule_schedule_proto_rawDescGZIP() []byte {
	file_inventory_api_proto_schedule_schedule_proto_rawDescOnce.Do(func() {
		file_inventory_api_proto_schedule_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_api_proto_schedule_schedule_proto_rawDesc), len(file_inventory_api_proto_schedule_schedule_proto_rawDesc)))
	})
	return file_inventory_api_proto_schedule_schedule_proto_rawDescData
}

var file_inventory_api_proto_schedule_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventory_api_proto_schedule_schedule_proto_goTypes = []any{
	(*SearchScheduleRequest)(nil),  // 0: SearchScheduleRequest
	(*SearchScheduleResponse)(nil), // 1: SearchScheduleResponse
	(*TrainScheduleItem)(nil),      // 2: TrainScheduleItem
}
var file_inventory_api_proto_schedule_schedule_proto_depIdxs = []int32{
	2, // 0: SearchScheduleResponse.schedules:type_name -> TrainScheduleItem
	0, // 1: TrainSchedule.Search:input_type -> SearchScheduleRequest
	1, // 2: TrainSchedule.Search:output_type -> SearchScheduleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inventory_api_proto_schedule_schedule_proto_init() }
func file_inventory_api_proto_schedule_schedule_proto_init() {
	if File_inventory_api_proto_schedule_schedule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_api_proto_schedule_schedule_proto_rawDesc), len(file_inventory_api_proto_schedule_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_api_proto_schedule_schedule_proto_goTypes,
		DependencyIndexes: file_inventory_api_proto_schedule_schedule_proto_depIdxs,
		MessageInfos:      file_inventory_api_proto_schedule_schedule_proto_msgTypes,
	}.Build()
	File_inventory_api_proto_schedule_schedule_proto = out.File
	file_inventory_api_proto_schedule_schedule_proto_goTypes = nil
	file_inventory_api_proto_schedule_schedule_proto_depIdxs = nil
}
