// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/labstack/echo/v4"
	"github.com/pujidjayanto/choochoohub/user-api/api"
	"sync"
)

// Ensure, that OtpApiMock does implement api.OtpApi.
// If this is not the case, regenerate this file with moq.
var _ api.OtpApi = &OtpApiMock{}

// OtpApiMock is a mock implementation of api.OtpApi.
//
//	func TestSomethingThatUsesOtpApi(t *testing.T) {
//
//		// make and configure a mocked api.OtpApi
//		mockedOtpApi := &OtpApiMock{
//			VerifyFunc: func(c echo.Context) error {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedOtpApi in code that requires api.OtpApi
//		// and then make assertions.
//
//	}
type OtpApiMock struct {
	// VerifyFunc mocks the Verify method.
	VerifyFunc func(c echo.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// C is the c argument value.
			C echo.Context
		}
	}
	lockVerify sync.RWMutex
}

// Verify calls VerifyFunc.
func (mock *OtpApiMock) Verify(c echo.Context) error {
	if mock.VerifyFunc == nil {
		panic("OtpApiMock.VerifyFunc: method is nil but OtpApi.Verify was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(c)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedOtpApi.VerifyCalls())
func (mock *OtpApiMock) VerifyCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}
