// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/pujidjayanto/choochoohub/user-api/dto"
	"github.com/pujidjayanto/choochoohub/user-api/model"
	"github.com/pujidjayanto/choochoohub/user-api/usecase"
	"sync"
)

// Ensure, that OtpUsecaseMock does implement usecase.OtpUsecase.
// If this is not the case, regenerate this file with moq.
var _ usecase.OtpUsecase = &OtpUsecaseMock{}

// OtpUsecaseMock is a mock implementation of usecase.OtpUsecase.
//
//	func TestSomethingThatUsesOtpUsecase(t *testing.T) {
//
//		// make and configure a mocked usecase.OtpUsecase
//		mockedOtpUsecase := &OtpUsecaseMock{
//			CreateFunc: func(c context.Context, req dto.OtpRequest) (*model.UserOtp, error) {
//				panic("mock out the Create method")
//			},
//			VerifyOtpFunc: func(c context.Context, req dto.VerifyOtpRequest) error {
//				panic("mock out the VerifyOtp method")
//			},
//		}
//
//		// use mockedOtpUsecase in code that requires usecase.OtpUsecase
//		// and then make assertions.
//
//	}
type OtpUsecaseMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(c context.Context, req dto.OtpRequest) (*model.UserOtp, error)

	// VerifyOtpFunc mocks the VerifyOtp method.
	VerifyOtpFunc func(c context.Context, req dto.VerifyOtpRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// C is the c argument value.
			C context.Context
			// Req is the req argument value.
			Req dto.OtpRequest
		}
		// VerifyOtp holds details about calls to the VerifyOtp method.
		VerifyOtp []struct {
			// C is the c argument value.
			C context.Context
			// Req is the req argument value.
			Req dto.VerifyOtpRequest
		}
	}
	lockCreate    sync.RWMutex
	lockVerifyOtp sync.RWMutex
}

// Create calls CreateFunc.
func (mock *OtpUsecaseMock) Create(c context.Context, req dto.OtpRequest) (*model.UserOtp, error) {
	if mock.CreateFunc == nil {
		panic("OtpUsecaseMock.CreateFunc: method is nil but OtpUsecase.Create was just called")
	}
	callInfo := struct {
		C   context.Context
		Req dto.OtpRequest
	}{
		C:   c,
		Req: req,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(c, req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedOtpUsecase.CreateCalls())
func (mock *OtpUsecaseMock) CreateCalls() []struct {
	C   context.Context
	Req dto.OtpRequest
} {
	var calls []struct {
		C   context.Context
		Req dto.OtpRequest
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// VerifyOtp calls VerifyOtpFunc.
func (mock *OtpUsecaseMock) VerifyOtp(c context.Context, req dto.VerifyOtpRequest) error {
	if mock.VerifyOtpFunc == nil {
		panic("OtpUsecaseMock.VerifyOtpFunc: method is nil but OtpUsecase.VerifyOtp was just called")
	}
	callInfo := struct {
		C   context.Context
		Req dto.VerifyOtpRequest
	}{
		C:   c,
		Req: req,
	}
	mock.lockVerifyOtp.Lock()
	mock.calls.VerifyOtp = append(mock.calls.VerifyOtp, callInfo)
	mock.lockVerifyOtp.Unlock()
	return mock.VerifyOtpFunc(c, req)
}

// VerifyOtpCalls gets all the calls that were made to VerifyOtp.
// Check the length with:
//
//	len(mockedOtpUsecase.VerifyOtpCalls())
func (mock *OtpUsecaseMock) VerifyOtpCalls() []struct {
	C   context.Context
	Req dto.VerifyOtpRequest
} {
	var calls []struct {
		C   context.Context
		Req dto.VerifyOtpRequest
	}
	mock.lockVerifyOtp.RLock()
	calls = mock.calls.VerifyOtp
	mock.lockVerifyOtp.RUnlock()
	return calls
}
