// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/user_test.go
//
// Generated by this command:
//
//	mockgen -source=./repository/user_test.go -package=mocks -destination=./mocks/mock_user_test.go
//

// Package mocks is a generated GoMock package.
package mocks
