// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/envloader/envloader.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/envloader/envloader.go -package=mocks -destination=./mocks/mock_envloader.go
//

// Package mocks is a generated GoMock package.
package mocks
