// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/logger/logrus.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/logger/logrus.go -package=mocks -destination=./mocks/mock_logger.go
//

// Package mocks is a generated GoMock package.
package mocks
