// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/schedule.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrainSchedule_Search_FullMethodName = "/TrainSchedule/Search"
)

// TrainScheduleClient is the client API for TrainSchedule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainScheduleClient interface {
	Search(ctx context.Context, in *SearchScheduleRequest, opts ...grpc.CallOption) (*SearchScheduleResponse, error)
}

type trainScheduleClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainScheduleClient(cc grpc.ClientConnInterface) TrainScheduleClient {
	return &trainScheduleClient{cc}
}

func (c *trainScheduleClient) Search(ctx context.Context, in *SearchScheduleRequest, opts ...grpc.CallOption) (*SearchScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchScheduleResponse)
	err := c.cc.Invoke(ctx, TrainSchedule_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainScheduleServer is the server API for TrainSchedule service.
// All implementations must embed UnimplementedTrainScheduleServer
// for forward compatibility.
type TrainScheduleServer interface {
	Search(context.Context, *SearchScheduleRequest) (*SearchScheduleResponse, error)
	mustEmbedUnimplementedTrainScheduleServer()
}

// UnimplementedTrainScheduleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainScheduleServer struct{}

func (UnimplementedTrainScheduleServer) Search(context.Context, *SearchScheduleRequest) (*SearchScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedTrainScheduleServer) mustEmbedUnimplementedTrainScheduleServer() {}
func (UnimplementedTrainScheduleServer) testEmbeddedByValue()                       {}

// UnsafeTrainScheduleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainScheduleServer will
// result in compilation errors.
type UnsafeTrainScheduleServer interface {
	mustEmbedUnimplementedTrainScheduleServer()
}

func RegisterTrainScheduleServer(s grpc.ServiceRegistrar, srv TrainScheduleServer) {
	// If the following call pancis, it indicates UnimplementedTrainScheduleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrainSchedule_ServiceDesc, srv)
}

func _TrainSchedule_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainScheduleServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainSchedule_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainScheduleServer).Search(ctx, req.(*SearchScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainSchedule_ServiceDesc is the grpc.ServiceDesc for TrainSchedule service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainSchedule_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TrainSchedule",
	HandlerType: (*TrainScheduleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _TrainSchedule_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/schedule.proto",
}
