// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/station.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListStationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStationsRequest) Reset() {
	*x = ListStationsRequest{}
	mi := &file_proto_station_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsRequest) ProtoMessage() {}

func (x *ListStationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsRequest.ProtoReflect.Descriptor instead.
func (*ListStationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{0}
}

type ListStationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stations      []*StationItem         `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStationsResponse) Reset() {
	*x = ListStationsResponse{}
	mi := &file_proto_station_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsResponse) ProtoMessage() {}

func (x *ListStationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsResponse.ProtoReflect.Descriptor instead.
func (*ListStationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{1}
}

func (x *ListStationsResponse) GetStations() []*StationItem {
	if x != nil {
		return x.Stations
	}
	return nil
}

type StationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationItem) Reset() {
	*x = StationItem{}
	mi := &file_proto_station_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationItem) ProtoMessage() {}

func (x *StationItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_station_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationItem.ProtoReflect.Descriptor instead.
func (*StationItem) Descriptor() ([]byte, []int) {
	return file_proto_station_proto_rawDescGZIP(), []int{2}
}

func (x *StationItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StationItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StationItem) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_proto_station_proto protoreflect.FileDescriptor

const file_proto_station_proto_rawDesc = "" +
	"\n" +
	"\x13proto/station.proto\"\x15\n" +
	"\x13ListStationsRequest\"@\n" +
	"\x14ListStationsResponse\x12(\n" +
	"\bstations\x18\x01 \x03(\v2\f.StationItemR\bstations\"Y\n" +
	"\vStationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city2M\n" +
	"\x0eStationService\x12;\n" +
	"\fListStations\x12\x14.ListStationsRequest\x1a\x15.ListStationsResponseB9Z7github.com/pujidjayanto/choochoohub/inventory-api/protob\x06proto3"

var (
	file_proto_station_proto_rawDescOnce sync.Once
	file_proto_station_proto_rawDescData []byte
)

func file_proto_station_proto_rawDescGZIP() []byte {
	file_proto_station_proto_rawDescOnce.Do(func() {
		file_proto_station_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_station_proto_rawDesc), len(file_proto_station_proto_rawDesc)))
	})
	return file_proto_station_proto_rawDescData
}

var file_proto_station_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_station_proto_goTypes = []any{
	(*ListStationsRequest)(nil),  // 0: ListStationsRequest
	(*ListStationsResponse)(nil), // 1: ListStationsResponse
	(*StationItem)(nil),          // 2: StationItem
}
var file_proto_station_proto_depIdxs = []int32{
	2, // 0: ListStationsResponse.stations:type_name -> StationItem
	0, // 1: StationService.ListStations:input_type -> ListStationsRequest
	1, // 2: StationService.ListStations:output_type -> ListStationsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_station_proto_init() }
func file_proto_station_proto_init() {
	if File_proto_station_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_station_proto_rawDesc), len(file_proto_station_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_station_proto_goTypes,
		DependencyIndexes: file_proto_station_proto_depIdxs,
		MessageInfos:      file_proto_station_proto_msgTypes,
	}.Build()
	File_proto_station_proto = out.File
	file_proto_station_proto_goTypes = nil
	file_proto_station_proto_depIdxs = nil
}
