name: Go - User API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-user-api:
    runs-on: ubuntu-latest

    # Spin up Postgres for CI tests
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
          POSTGRES_DB: user_api_test
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: user-api

    steps:
      - uses: actions/checkout@v4

      - name: Copy CI env file
        run: cp .env.ci .env

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'
          cache-dependency-path: subdir/go.sum

      - name: Download Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...
