name: Go - User API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-user-api:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
          POSTGRES_DB: user_api_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ci_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: user-api

    steps:
      - uses: actions/checkout@v4

      - name: Create .env for CI
        run: |
          cat <<EOF > .env
          TEST_DB_HOST=127.0.0.1
          TEST_DB_PORT=5432
          TEST_DB_USER=ci_user
          TEST_DB_PASSWORD=ci_password
          TEST_DB_NAME=user_api_test
          TEST_DB_SSL_MODE=disable
          EOF

      # Set up Go with caching
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'
          cache-dependency-path: user-api/go.sum

      # Download dependencies
      - name: Download Dependencies
        run: go mod download

      # Run database migrations
      - name: Run database migrations
        run: |
          for f in migrations/*.sql; do
            PGPASSWORD=$TEST_DB_PASSWORD psql -h $TEST_DB_HOST -U $TEST_DB_USER -d $TEST_DB_NAME -f "$f"
          done

      # Run tests
      - name: Run Tests
        run: go test -v ./...
