name: Go - User API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-user-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-api  # Run commands inside user-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Test User API
        run: go test -v ./...
