name: Go - User API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-user-api:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
          POSTGRES_DB: user_api_test
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: user-api

    steps:
      - uses: actions/checkout@v4

      - name: Copy CI env file
        run: cp .env.ci .env

      # Set up Go with caching
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'
          cache-dependency-path: go.sum

      - name: Download Dependencies
        run: go mod download

      - name: Build Migration Binary
        run: go build -o migration ./cmd/migration

      - name: Run database migrations with Migrator
        run: |
          set -a
          source .env
          set +a
          # DEBUG: Echo all environment variables to confirm they are set
          echo "--- Environment Variables for Migrator ---"
          echo "TEST_DB_HOST: ${TEST_DB_HOST}"
          echo "TEST_DB_PORT: ${TEST_DB_PORT}"
          echo "TEST_DB_USER: ${TEST_DB_USER}"
          echo "TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}"
          echo "TEST_DB_NAME: ${TEST_DB_NAME}"
          echo "TEST_DB_SSL_MODE: ${TEST_DB_SSL_MODE}"
          echo "SERVER_ENV: ${SERVER_ENV}"
          echo "------------------------------------------"
          echo "Running migration binary..."

          ./migration -migrate up

      - name: Run Tests
        run: go test -v ./...
